services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: jedi_nginx_proxy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ${CAMINHO_PROJETO_ADIANTI}:/var/www/html
      - ../jedi-site/backend/site:/var/www/html/site
      # MAPEAMENTO DIRETO: Faz o /public/storage do Nginx ler a pasta real do storage
      - ../jedi-site/backend/site/storage/app/public:/var/www/html/site/public/storage
      - graficos_data:/var/www/html/mad/app/output/charts:ro
    networks:
      jedieduca-network:
        aliases:
          - api.dev.jedieduca.com.br

volumes:
  graficos_data:
    name: jedi-python_graficos_data
    external: true

networks:
  jedieduca-network:
    external: true